#!/bin/sh
# Copyright 2018 Łukasz Niemier

# Permission to use, copy, modify, and/or distribute this software for any purpose
# with or without fee is hereby granted, provided that the above copyright notice
# and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
# THIS SOFTWARE.

exec psql -1qX "$@" <<EOF
\timing off

\echo '=========================== MISSING INDICES ===========================\n'
SELECT
    relname AS "Table name",
    usage_percentage "Indices usage overall scans"
FROM (
    SELECT
    relname,
    round(idx_scan * 100.0 / NULLIF(idx_scan + seq_scan, 0), 2) AS usage_percentage,
    (seq_scan + idx_scan) / avg(seq_scan + idx_scan) OVER () AS overall_percentage
    FROM pg_stat_user_tables tbl
) tbl
WHERE usage_percentage < 90
    AND overall_percentage > 0.01
ORDER BY usage_percentage DESC;
EOF
